name: Update README with blog posts

on:
  schedule:
    - cron: '0 */12 * * *'  # 12시간마다 실행
  workflow_dispatch:        # 수동 실행 가능

permissions:
  contents: write           # <-- 요 줄이 핵심!

jobs:
  update-blog-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4     # v4로 업데이트

      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://woosunghyeon03.github.io/feed.xml"
          max_post_count: 5
          commit_message: "chore: update blog posts in README"
